### ISSUE TITLE
Django 4.0 ugettext_lazy removed

### ISSUE THREAD

**Issue by luishiguera** [eshaan7/django-rest-durin#24]
in `models.py`

`from django.utils.translation import ugettext_lazy as _` no longer works

https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0
- django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy() are removed.

**Comment by eshaan7** [comment]
Hi. Thanks for the report.

At the moment, this package does not work with Django >=4.0. We need to enable ci/tests for Django 4.x and fix the bugs to make it work.

**Comment by eshaan7** [comment]
Please update to ``django-rest-durin==0.4.0`` ([pypi link](https://pypi.org/project/django-rest-durin/0.4.0/)).
